# Generated by Django 3.0.3 on 2020-02-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст сообщения')),
                ('rate', models.IntegerField(default=0, verbose_name='Оценка сообщения')),
                ('status', models.IntegerField(choices=[(0, 'Не прочитано'), (1, 'Принятно'), (2, 'Отклонено')], default=0, verbose_name='Статус отзыва')),
            ],
            options={
                'verbose_name': 'Отзывы об обучении',
            },
        ),
    ]
